{{/*
  AUTO-GENERATED by hack/update-apiserver-templates.sh. DO NOT EDIT MANUALLY.
  Resolves the dashboard apiserver image, defaulting to the manager image when
  apiserver.image overrides are not set (the apiserver and controller share one image).
*/}}
{{- define "promoter.apiserver.image" -}}
{{- $img := .Values.apiserver.image | default dict -}}
{{- $repo := $img.repository | default .Values.manager.image.repository -}}
{{- $tag := $img.tag | default .Values.manager.image.tag | default .Chart.AppVersion -}}
{{- if contains "@" $repo -}}
{{- $repo -}}
{{- else -}}
{{- printf "%s:%s" $repo $tag -}}
{{- end -}}
{{- end -}}
