apiVersion: promoter.argoproj.io/v1alpha1
kind: ControllerConfiguration
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "promoter.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    control-plane: controller-manager
  name: promoter-controller-configuration
  namespace: {{ .Release.Namespace }}
spec:
{{- omit .Values.controllerConfiguration "pullRequest" | toYaml | nindent 2 }}
  pullRequest:
{{- omit .Values.controllerConfiguration.pullRequest "template" | toYaml | nindent 4 }}
    template:
      title: "Promote {{ "{{" }} trunc 5 .ChangeTransferPolicy.Status.Proposed.Dry.Sha {{ "}}" }} to `{{ "{{" }} .ChangeTransferPolicy.Spec.ActiveBranch {{ "}}" }}`"
      description: "This PR is promoting the environment branch `{{ "{{" }} .ChangeTransferPolicy.Spec.ActiveBranch {{ "}}" }}` which is currently on dry sha {{ "{{" }} .ChangeTransferPolicy.Status.Active.Dry.Sha {{ "}}" }} to dry sha {{ "{{" }} .ChangeTransferPolicy.Status.Proposed.Dry.Sha {{ "}}" }}."
